name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
            cd /home/ubuntu
            if [ ! -d "fastapi-book-project" ]; then
                git clone https://github.com/Peacepearl/fastapi-book-project.git
            fi
            cd fastapi-book-project
            git pull
            sudo apt update
            if ! command -v docker &> /dev/null; then
                sudo apt install -y docker.io
            fi
            if ! command -v docker-compose &> /dev/null; then
                sudo apt install -y docker-compose
            fi
            sudo docker-compose down
            sudo docker-compose up -d --build